#restore desktop wallpaper
nitrogen --restore &
#compositor for transparency
picom &
#path to custom status bar (dwm bar)script
 /home/invalid/Applications/scripts/dwm-bar/dwm_bar.sh &
#loop dwm so that exitting/logging out dwm is not required to take the changes effect
while true; do
        dwm >/dev/null 2>&1
done
#set brightness to 1 using xbacklight package
xbacklight -set 1
#execute dwm
exec dwm
